### ISSUE TITLE
FormsFeeder build error - testDecode{TestScenario}[6]

### ISSUE THREAD

**Issue by codedragonfist** [4PointSolutions/FormsFeeder#8]
maven package or install command is getting failed while building the FormsFeeder parent project due to failure in the unit test on Mac machines.

Workaround is by skipping the unit test. e,g _mvn -DskipTests=true package or mvn -DskipTests=true install_

ERROR] Tests run: 18, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.099 s <<< FAILURE! - in com._4point.aem.formsfeeder.core.datasource.serialization.XmlDataSourceListDecoderTest
[ERROR] testDecode{TestScenario}[6]  Time elapsed: 0.012 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: DataSource 'filename' fields do not match. ==> expected: <Optional[dir/filename]> but was: <Optional[dir\filename]>
	at com._4point.aem.formsfeeder.core.datasource.serialization.XmlDataSourceListDecoderTest.dsEquals(XmlDataSourceListDecoderTest.java:159)
	at com._4point.aem.formsfeeder.core.datasource.serialization.XmlDataSourceListDecoderTest.dslEquals(XmlDataSourceListDecoderTest.java:152)
	at com._4point.aem.formsfeeder.core.datasource.serialization.XmlDataSourceListDecoderTest.testDecode(XmlDataSourceListDecoderTest.java:43)

[INFO] Running com._4point.aem.formsfeeder.core.datasource.serialization.XmlDataSourceListEncoderTest
[ERROR] Tests run: 11, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.024 s <<< FAILURE! - in com._4point.aem.formsfeeder.core.datasource.serialization.XmlDataSourceListEncoderTest
[ERROR] test_OutputStream  Time elapsed: 0.008 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <<?xml version="1.0" ?><DataSourceList><DataSource Name="DsName1" ContentType="text/plain; charset=UTF-8"><Content>RHNWYWx1ZTE=</Content></DataSource><DataSource Name="DsName2" ContentType="text/plain; charset=UTF-8"><Attribute Name="Ds2Attr1" Value="Ds2AttrValue1"/><Content>Mg==</Content></DataSource><DataSource Name="DSName3" ContentType="application/pdf" Filename="dir\filename"><Attribute Name="Ds3Attr1" Value="Ds3AttrValue1"/><Content>RFNWYWx1ZTM=</Content></DataSource><DataSource Name="DSName4" ContentType="text/plain; charset=UTF-8"><Attribute Name="Ds4Attr1" Value="Ds4AttrValue1"/><Content>RFNWYWx1ZTRfMQ==</Content></DataSource><DataSource Name="DSName4" ContentType="text/plain; charset=UTF-8"><Attribute Name="Ds4Attr1" Value="Ds4AttrValue1"/><Content>RFNWYWx1ZTRfMg==</Content></DataSource><DataSource Name="DSName5" ContentType="text/html"><Attribute Name="Ds5Attr3" Value="Ds5AttrValue3"/><Attribute Name="Ds5Attr2" Value="Ds5AttrValue2"/><Attribute Name="Ds5Attr1" Value="Ds5AttrValue1"/><Content>RFM1Q29udGVudDE=</Content></DataSource><DataSource Name="DSName5" ContentType="text/html"><Attribute Name="Ds5Attr3" Value="Ds5AttrValue3"/><Attribute Name="Ds5Attr2" Value="Ds5AttrValue2"/><Attribute Name="Ds5Attr1" Value="Ds5AttrValue1"/><Content>RFM1Q29udGVudDI=</Content></DataSource></DataSourceList>> but was: <<?xml version="1.0" ?><DataSourceList><DataSource Name="DsName1" ContentType="text/plain; charset=UTF-8"><Content>RHNWYWx1ZTE=</Content></DataSource><DataSource Name="DsName2" ContentType="text/plain; charset=UTF-8"><Attribute Name="Ds2Attr1" Value="Ds2AttrValue1"/><Content>Mg==</Content></DataSource><DataSource Name="DSName3" ContentType="application/pdf" Filename="dir/filename"><Attribute Name="Ds3Attr1" Value="Ds3AttrValue1"/><Content>RFNWYWx1ZTM=</Content></DataSource><DataSource Name="DSName4" ContentType="text/plain; charset=UTF-8"><Attribute Name="Ds4Attr1" Value="Ds4AttrValue1"/><Content>RFNWYWx1ZTRfMQ==</Content></DataSource><DataSource Name="DSName4" ContentType="text/plain; charset=UTF-8"><Attribute Name="Ds4Attr1" Value="Ds4AttrValue1"/><Content>RFNWYWx1ZTRfMg==</Content></DataSource><DataSource Name="DSName5" ContentType="text/html"><Attribute Name="Ds5Attr3" Value="Ds5AttrValue3"/><Attribute Name="Ds5Attr2" Value="Ds5AttrValue2"/><Attribute Name="Ds5Attr1" Value="Ds5AttrValue1"/><Content>RFM1Q29udGVudDE=</Content></DataSource><DataSource Name="DSName5" ContentType="text/html"><Attribute Name="Ds5Attr3" Value="Ds5AttrValue3"/><Attribute Name="Ds5Attr2" Value="Ds5AttrValue2"/><Attribute Name="Ds5Attr1" Value="Ds5AttrValue1"/><Content>RFM1Q29udGVudDI=</Content></DataSource></DataSourceList>>
	at com._4point.aem.formsfeeder.core.datasource.serialization.XmlDataSourceListEncoderTest.test_OutputStream(XmlDataSourceListEncoderTest.java:69)

[ERROR] testEncode{TestScenario}[6]  Time elapsed: 0.001 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <<?xml version="1.0" ?><DataSourceList><DataSource Name="DSName3" ContentType="application/pdf" Filename="dir\filename"><Attribute Name="Ds3Attr1" Value="Ds3AttrValue1"/><Content>RFNWYWx1ZTM=</Content></DataSource></DataSourceList>> but was: <<?xml version="1.0" ?><DataSourceList><DataSource Name="DSName3" ContentType="application/pdf" Filename="dir/filename"><Attribute Name="Ds3Attr1" Value="Ds3AttrValue1"/><Content>RFNWYWx1ZTM=</Content></DataSource></DataSourceList>>
	at com._4point.aem.formsfeeder.core.datasource.serialization.XmlDataSourceListEncoderTest.testEncode(XmlDataSourceListEncoderTest.java:42)

**Comment by rmcdouga** [comment]
It appears that one or more of the DataSource tests in the formsfeeder.core project are sensitive to the filesystem separator character.  This should be a fairly easy fix to make.
